# Generated by Django 4.1.6 on 2023-02-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created',
            new_name='url',
        ),
    ]
