# Generated by Django 3.2.18 on 2023-03-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_extensionuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=14)),
                ('rating_reason', models.CharField(max_length=40)),
            ],
        ),
    ]
